default_install_hook_types: [pre-commit, prepare-commit-msg]
ci:
  autofix_commit_msg: ":rotating_light: auto fix by pre-commit hooks"
  autofix_prs: true
  autoupdate_branch: master
  autoupdate_schedule: monthly
  autoupdate_commit_msg: ":arrow_up: auto update by pre-commit hooks"
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.1
    hooks:
      - id: clang-format
        args: [--style=file, -i, core/*.cpp, -i, core/*.h]
        stages: [pre-commit]

  - repo: https://github.com/nonebot/nonemoji
    rev: v0.1.4
    hooks:
      - id: nonemoji
        stages: [prepare-commit-msg]